import type { Metadata } from "next";
import { Montserrat, Titillium_Web, Urbanist } from "next/font/google";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import "./globals.scss";
import Header from "./components/Header";
import Footer from "./components/Footer";

config.autoAddCss = false

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
})

const titilliumWeb = Titillium_Web({
  weight: '600',
  variable: "--font-titillium-web",
  subsets: ["latin"],
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Crackerjack Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${titilliumWeb.variable} ${urbanist.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
