name: Deploy Dev Site to Siteground

on:
  push:
    branches: [dev]

  workflow_dispatch:

concurrency:
  group: deploy-dev-site
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add pnpm
        run: npm i -g pnpm

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Build static site
        env:
          NEXT_PUBLIC_GTM_ID: GTM-TH5JV84B
          NEXT_PUBLIC_SANITY_PROJECT_ID: kn74ytrq
        run: |
          pnpm --filter web copy-consent
          pnpm --filter web build

      - name: Add to Github
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          cd web

          git clone -b dev ---single-branch https://mattfishcodes:${DEPLOY_TOKEN}@github.com/mattfishcodes/crackerjack-solutions-siteground.git prod

          rsync -av --delete --exclude '.git/' out/ prod/

          cd prod
          git config user.name "deploy-bot"
          git config user.email "deploy@bot.com"

          git add .

          git commit -m "Deploy $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"

          git push origin dev

      - name: SSH to Siteground
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd www/devstaging.crackerjacksolutions.com/public_html
            git pull
